from dotenv import load_dotenv
import os

# Load environment variables from a .env file
load_dotenv()

# Access values from the .env file
FINNHUB_API_KEY = os.getenv('FINNHUB_API_KEY')
ALPHA_VANTAGE_API_KEY = os.getenv('ALPHA_VANTAGE_API_KEY')
DATABASE_FILE_PATH = os.getenv('DATABASE_FILE_PATH')
USE_FIREBASE = os.getenv('USE_FIREBASE')
GOOGLE_APPLICATION_CREDENTIALS = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
FIREBASE_WEB_API_KEY = os.getenv('FIREBASE_WEB_API_KEY')
FIREBASE_AUTH_DOMAIN = os.getenv('FIREBASE_AUTH_DOMAIN')
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID')
FIREBASE_DATABASE_URL = os.getenv('FIREBASE_DATABASE_URL')



# Print the values
print(f"FINNHUB_API_KEY: {FINNHUB_API_KEY}")
print(f"ALPHA_VANTAGE_API_KEY: {ALPHA_VANTAGE_API_KEY}")
print(f"DATABASE_FILE_PATH: {DATABASE_FILE_PATH}")
print(f"USE_FIREBASE: {USE_FIREBASE}")
print(f"GOOGLE_APPLICATION_CREDENTIALS: {GOOGLE_APPLICATION_CREDENTIALS}")
print(f"FIREBASE_WEB_API_KEY: {FIREBASE_WEB_API_KEY}")
print(f"FIREBASE_AUTH_DOMAIN: {FIREBASE_AUTH_DOMAIN}")
print(f"FIREBASE_PROJECT_ID: {FIREBASE_PROJECT_ID}")
print(f"FIREBASE_DATABASE_URL: {FIREBASE_DATABASE_URL}")

