INSERT INTO daily_quiz (date, question, possible_answer_1, possible_answer_2, possible_answer_3, correct_answer)
VALUES
('2025-05-14', 'What is the stock market?', 'A place to buy and sell stocks', 'A place to store goods', 'A type of bank', 'A place to buy and sell stocks'),
('2025-05-15', 'What does IPO stand for?', 'Initial Public Offering', 'International Payment Order', 'Investment Portfolio Option', 'Initial Public Offering'),
('2025-05-16', 'What is a bond?', 'A loan to a company or government', 'A type of stock', 'A savings account', 'A loan to a company or government'),
('2025-05-17', 'What does the term "bull market" mean?', 'A market where prices are rising', 'A market where prices are falling', 'A market with no activity', 'A market where prices are rising'),
('2025-05-18', 'What is diversification in investing?', 'Spreading investments across different assets', 'Investing all money in one stock', 'Avoiding investments', 'Spreading investments across different assets'),
('2025-05-19', 'What is the S&P 500?', 'An index of 500 large companies', 'A type of bond', 'A government agency', 'An index of 500 large companies'),
('2025-05-20', 'What does the term "liquidity" mean in finance?', 'How easily an asset can be converted to cash', 'The amount of water in a company', 'The size of a company', 'How easily an asset can be converted to cash'),
('2025-05-21', 'What is a mutual fund?', 'A pool of money from many investors', 'A type of bank account', 'A government bond', 'A pool of money from many investors'),
('2025-05-22', 'What is the primary purpose of a stock exchange?', 'To facilitate buying and selling of stocks', 'To store physical goods', 'To issue loans', 'To facilitate buying and selling of stocks'),
('2025-05-23', 'What is a dividend?', 'A payment made to shareholders', 'A type of tax', 'A stock split', 'A payment made to shareholders'),
('2025-05-24', 'What is the role of a financial advisor?', 'To provide investment advice', 'To manage a company', 'To issue loans', 'To provide investment advice'),
('2025-05-25', 'What does the term "bear market" mean?', 'A market where prices are falling', 'A market where prices are rising', 'A market with no activity', 'A market where prices are falling'),
('2025-05-26', 'What is the difference between a stock and a bond?', 'Stocks represent ownership, bonds are loans', 'Stocks are loans, bonds are ownership', 'They are the same', 'Stocks represent ownership, bonds are loans'),
('2025-05-27', 'What is the foreign exchange market?', 'A market for trading currencies', 'A market for trading stocks', 'A market for trading bonds', 'A market for trading currencies'),
('2025-05-28', 'What is a hedge fund?', 'A private investment fund for wealthy investors', 'A government savings plan', 'A type of bond', 'A private investment fund for wealthy investors'),
('2025-05-29', 'What is the purpose of a central bank?', 'To manage a country’s currency and monetary policy', 'To issue stocks', 'To provide loans to individuals', 'To manage a country’s currency and monetary policy'),
('2025-05-30', 'What is an ETF?', 'Exchange-Traded Fund', 'Electronic Transfer Fund', 'Equity Trading Fund', 'Exchange-Traded Fund'),
('2025-05-31', 'What does the term "market capitalization" mean?', 'The total value of a company’s shares', 'The amount of cash a company has', 'The number of employees in a company', 'The total value of a company’s shares'),
('2025-06-01', 'What is a blue-chip stock?', 'A stock from a well-established company', 'A stock with high risk', 'A stock with no value', 'A stock from a well-established company'),
('2025-06-02', 'What is the role of a stockbroker?', 'To buy and sell stocks on behalf of clients', 'To manage a company', 'To issue loans', 'To buy and sell stocks on behalf of clients'),
('2025-06-03', 'What is a financial derivative?', 'A contract based on the value of an underlying asset', 'A type of stock', 'A savings account', 'A contract based on the value of an underlying asset'),
('2025-06-04', 'What is the purpose of a credit rating agency?', 'To assess the creditworthiness of borrowers', 'To issue loans', 'To manage investments', 'To assess the creditworthiness of borrowers'),
('2025-06-05', 'What does the term "portfolio" mean in finance?', 'A collection of investments', 'A type of bond', 'A savings account', 'A collection of investments'),
('2025-06-06', 'What is the difference between a primary and secondary market?', 'Primary is for new securities, secondary is for existing ones', 'Primary is for bonds, secondary is for stocks', 'They are the same', 'Primary is for new securities, secondary is for existing ones'),
('2025-06-07', 'What is the role of the Federal Reserve?', 'To regulate monetary policy in the US', 'To issue stocks', 'To provide loans to individuals', 'To regulate monetary policy in the US'),
('2025-06-08', 'What is a stock split?', 'Dividing existing shares into multiple shares', 'Merging two companies', 'Selling all shares', 'Dividing existing shares into multiple shares'),
('2025-06-09', 'What is the purpose of a financial statement?', 'To provide information about a company’s financial performance', 'To issue loans', 'To manage investments', 'To provide information about a company’s financial performance'),
('2025-06-10', 'What is the difference between a public and private company?', 'Public companies trade shares on stock exchanges, private companies do not', 'Private companies trade shares on stock exchanges, public companies do not', 'They are the same', 'Public companies trade shares on stock exchanges, private companies do not')
ON CONFLICT (date) DO NOTHING;
