INSERT INTO daily_quiz (date, question, possible_answer_1, possible_answer_2, possible_answer_3, correct_answer) VALUES
('2025-05-14', 'What is the main function of a stock exchange?', 'To provide loans to companies', 'To facilitate the buying and selling of securities', 'To set interest rates', 'To facilitate the buying and selling of securities'),
('2025-05-15', 'Which of the following is considered a safe-haven asset?', 'Emerging market stocks', 'Gold', 'High-yield bonds', 'Gold'),
('2025-05-16', 'What does IPO stand for?', 'Initial Price Offering', 'Initial Public Offering', 'International Portfolio Option', 'Initial Public Offering'),
('2025-05-17', 'Which index tracks 500 large US companies?', 'FTSE 100', 'S&P 500', 'Nikkei 225', 'S&P 500'),
('2025-05-18', 'What is a bear market?', 'A market with rising prices', 'A market with falling prices', 'A market with stable prices', 'A market with falling prices'),
('2025-05-19', 'Which currency is most traded globally?', 'Euro', 'Japanese Yen', 'US Dollar', 'US Dollar'),
('2025-05-20', 'What is the main risk of investing in bonds?', 'Credit risk', 'Liquidity risk', 'Currency risk', 'Credit risk'),
('2025-05-21', 'Which of these is a derivative instrument?', 'Mutual fund', 'Option', 'Treasury bill', 'Option'),
('2025-05-22', 'What does diversification help reduce?', 'Expected return', 'Risk', 'Dividends', 'Risk'),
('2025-05-23', 'Which market is open 24 hours during weekdays?', 'Stock market', 'Forex market', 'Commodity market', 'Forex market'),
('2025-05-24', 'What is a blue chip stock?', 'A stock of a small startup', 'A stock of a large, established company', 'A government bond', 'A stock of a large, established company'),
('2025-05-25', 'Which of the following is NOT an equity index?', 'Dow Jones', 'NASDAQ', 'LIBOR', 'LIBOR'),
('2025-05-26', 'What is the main purpose of a central bank?', 'To regulate stock prices', 'To manage a country’s monetary policy', 'To issue corporate bonds', 'To manage a country’s monetary policy'),
('2025-05-27', 'Which country is home to the world’s largest stock exchange by market capitalization?', 'Japan', 'United States', 'United Kingdom', 'United States'),
('2025-05-28', 'What does the term “liquidity” refer to in financial markets?', 'The amount of cash a company holds', 'The ease of buying or selling an asset without affecting its price', 'The number of shares outstanding', 'The ease of buying or selling an asset without affecting its price'),
('2025-05-29', 'Which of these is a fixed-income security?', 'Common stock', 'Corporate bond', 'Real estate', 'Corporate bond'),
('2025-05-30', 'What is the main advantage of an ETF over a mutual fund?', 'ETFs are actively managed', 'ETFs can be traded throughout the day', 'ETFs have higher fees', 'ETFs can be traded throughout the day'),
('2025-05-31', 'Which of the following is a commodity?', 'Apple stock', 'Crude oil', 'US Treasury bond', 'Crude oil'),
('2025-06-01', 'What is short selling?', 'Buying a stock to hold long-term', 'Selling a stock you do not own', 'Buying a bond at a discount', 'Selling a stock you do not own'),
('2025-06-02', 'Which financial instrument gives the holder the right, but not the obligation, to buy or sell an asset?', 'Option', 'Bond', 'Stock', 'Option');